default: &default
  adapter: mysql2
  encoding: utf8
  username: <%= ENV['DATABASE_USERNAME'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
  pool: 5

development:
  <<: *default
  database: ethereum-token-sample_development

test:
  <<: *default
  database: ethereum-token-sample_test
